# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-21 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20180719_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeout',
            field=models.IntegerField(default=30, verbose_name='任务超时'),
        ),
    ]
