# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20180721_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklog',
            options={'permissions': (('can_del_task_log', '可以删除子任务日志'),)},
        ),
    ]
