# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20180725_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklog',
            options={'permissions': (('can_display_task_log', '可以查看任务列表'), ('can_task_log_info', '可以删除子任务日志'), ('can_del_task_log', '可以删除子任务日志'))},
        ),
    ]
